server:
  port: 8080

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: auth-service
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/auth/**, /lists/**

            - id: project-service
              uri: lb://PROJECT-SERVICE
              predicates:
                - Path=/projets/**

            - id: event-service
              uri: lb://EVENT-SERVICE
              predicates:
                - Path=/events/**

            - id: notification-service
              uri: lb://NOTIFICATION-SERVICE
              predicates:
                - Path=/notifications/**

            - id: recommendation-service
              uri: lb://RECOMMENDATION-SERVICE
              predicates:
                - Path=/recommendations/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}